SELECT CB.[ID], CB.[KEY], CB.[DESCRIPTION] 
FROM [CONTENT_BLOCKS] CB 
WHERE CB.[IsDeleted] = 0 
	AND CB.[KEY] LIKE '%' + @PRM_CONTENT_BLOCK_KEY + '%' 
	AND CB.[IS_ACTIVE] = @PRM_CONTENT_BLOCK_IS_ACTIVE 
ORDER BY CB.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 