SELECT S.[ID], S.[NAME], S.[DEFAULT_LANGUAGE_ID], S.[THEME_ID] 
FROM [SITES] S 
WHERE S.[IsDeleted] = 0 
	AND S.[IS_ACTIVE] = @PRM_SITE_IS_ACTIVE 
ORDER BY S.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 