//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoCms.Common.Models;
using QuickCode.DemoCms.ContentManagementModule.Domain.Entities;
using QuickCode.DemoCms.ContentManagementModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.DemoCms.Common;
using QuickCode.DemoCms.Common.Extensions;
using QuickCode.DemoCms.Common.Helpers;
using QuickCode.DemoCms.ContentManagementModule.Persistence.Contexts;
using QuickCode.DemoCms.ContentManagementModule.Application.Dtos.BlockTranslation;
using QuickCode.DemoCms.ContentManagementModule.Application.Mappings;
using QuickCode.DemoCms.ContentManagementModule.Persistence.Sql;
using QuickCode.DemoCms.ContentManagementModule.Domain.Enums;

namespace QuickCode.DemoCms.ContentManagementModule.Persistence.Repositories
{
    public partial class BlockTranslationRepository : BaseRepository, IBlockTranslationRepository
    {
        public async Task<RepoResponse<List<GetByBlockIdResponseDto>>> GetByBlockIdAsync(int blockTranslationBlockId, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling("GetByBlockId", async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetByBlockIdResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.BlockTranslation.Query.GetByBlockId);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_BLOCK_TRANSLATION_BLOCK_ID = blockTranslationBlockId,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    using var connection = await GetOpenConnectionAsync(_readContext);
                    var values = await connection.QueryAsync<GetByBlockIdResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in BlockTranslation");
                }
            });
        }

        public async Task<RepoResponse<GetByBlockAndLanguageResponseDto>> GetByBlockAndLanguageAsync(int blockTranslationBlockId, string blockTranslationLanguageCode)
        {
            return await ExecuteWithExceptionHandling("GetByBlockAndLanguage", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.BlockTranslation.Query.GetByBlockAndLanguage);
                var parameters = new
                {
                    PRM_BLOCK_TRANSLATION_BLOCK_ID = blockTranslationBlockId,
                    PRM_BLOCK_TRANSLATION_LANGUAGE_CODE = blockTranslationLanguageCode
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<GetByBlockAndLanguageResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in BlockTranslation");
            });
        }
    }
}