// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuickCode.DemoCms.SiteManagementModule.Persistence.Contexts;

#nullable disable

namespace QuickCode.DemoCms.SiteManagementModule.Persistence.Migrations
{
    [DbContext(typeof(WriteDbContext))]
    partial class WriteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuickCode.DemoCms.SiteManagementModule.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<string>("Action")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ACTION");

                    b.Property<string>("ChangeSummary")
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CHANGE_SUMMARY");

                    b.Property<string>("ChangedColumns")
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CHANGED_COLUMNS");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CORRELATION_ID");

                    b.Property<string>("EntityId")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("ENTITY_ID");

                    b.Property<string>("EntityName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("ENTITY_NAME");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ERROR_MESSAGE");

                    b.Property<string>("Hash")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("HASH");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("IP_ADDRESS");

                    b.Property<bool>("IsChanged")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IS_CHANGED");

                    b.Property<bool>("IsSuccess")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IS_SUCCESS");

                    b.Property<string>("NewValues")
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NEW_VALUES");

                    b.Property<string>("OldValues")
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("OLD_VALUES");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2")
                        .HasColumnName("TIMESTAMP");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("USER_AGENT");

                    b.Property<string>("UserGroup")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("USER_GROUP");

                    b.Property<string>("UserId")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("USER_ID");

                    b.Property<string>("UserName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("USER_NAME");

                    b.HasKey("Id");

                    b.ToTable("AUDIT_LOGS");
                });

            modelBuilder.Entity("QuickCode.DemoCms.SiteManagementModule.Domain.Entities.Domain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedOnUtc");

                    b.Property<string>("Hostname")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("HOSTNAME");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("IS_ACTIVE");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IS_PRIMARY");

                    b.Property<int>("SiteId")
                        .HasColumnType("int")
                        .HasColumnName("SITE_ID");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("SiteId");

                    b.ToTable("DOMAINS");
                });

            modelBuilder.Entity("QuickCode.DemoCms.SiteManagementModule.Domain.Entities.NavigationItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedOnUtc");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<bool>("IsVisible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("IS_VISIBLE");

                    b.Property<string>("Label")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("LABEL");

                    b.Property<int>("MenuId")
                        .HasColumnType("int")
                        .HasColumnName("MENU_ID");

                    b.Property<int>("PageId")
                        .HasColumnType("int")
                        .HasColumnName("PAGE_ID");

                    b.Property<int>("ParentItemId")
                        .HasColumnType("int")
                        .HasColumnName("PARENT_ITEM_ID");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SORT_ORDER")
                        .HasDefaultValueSql("0");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("TYPE");

                    b.Property<string>("Url")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("URL");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("MenuId");

                    b.HasIndex("ParentItemId");

                    b.ToTable("NAVIGATION_ITEMS");
                });

            modelBuilder.Entity("QuickCode.DemoCms.SiteManagementModule.Domain.Entities.NavigationMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedOnUtc");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<string>("LocationKey")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LOCATION_KEY");

                    b.Property<string>("Name")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("NAME");

                    b.Property<int>("SiteId")
                        .HasColumnType("int")
                        .HasColumnName("SITE_ID");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("SiteId");

                    b.ToTable("NAVIGATION_MENUS");
                });

            modelBuilder.Entity("QuickCode.DemoCms.SiteManagementModule.Domain.Entities.Site", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATED_DATE");

                    b.Property<int>("DefaultLanguageId")
                        .HasColumnType("int")
                        .HasColumnName("DEFAULT_LANGUAGE_ID");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedOnUtc");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("IS_ACTIVE");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<string>("Name")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("NAME");

                    b.Property<int>("ThemeId")
                        .HasColumnType("int")
                        .HasColumnName("THEME_ID");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("ThemeId");

                    b.ToTable("SITES");
                });

            modelBuilder.Entity("QuickCode.DemoCms.SiteManagementModule.Domain.Entities.SiteLanguage", b =>
                {
                    b.Property<int>("SiteId")
                        .HasColumnType("int")
                        .HasColumnName("SITE_ID");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int")
                        .HasColumnName("LANGUAGE_ID");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("IS_ENABLED");

                    b.HasKey("SiteId", "LanguageId");

                    b.ToTable("SITE_LANGUAGES");
                });

            modelBuilder.Entity("QuickCode.DemoCms.SiteManagementModule.Domain.Entities.SiteSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedOnUtc");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<bool>("IsSecret")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IS_SECRET");

                    b.Property<string>("Key")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("KEY");

                    b.Property<int>("SiteId")
                        .HasColumnType("int")
                        .HasColumnName("SITE_ID");

                    b.Property<string>("Value")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("VALUE");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("SiteId");

                    b.ToTable("SITE_SETTINGS");
                });

            modelBuilder.Entity("QuickCode.DemoCms.SiteManagementModule.Domain.Entities.Template", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedOnUtc");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<string>("FilePath")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("FILE_PATH");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<string>("Key")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("KEY");

                    b.Property<string>("Name")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("NAME");

                    b.Property<int>("ThemeId")
                        .HasColumnType("int")
                        .HasColumnName("THEME_ID");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("ThemeId");

                    b.ToTable("TEMPLATES");
                });

            modelBuilder.Entity("QuickCode.DemoCms.SiteManagementModule.Domain.Entities.Theme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedOnUtc");

                    b.Property<string>("Developer")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("DEVELOPER");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("IS_ACTIVE");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<string>("Name")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("NAME");

                    b.Property<string>("RepositoryUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("REPOSITORY_URL");

                    b.Property<string>("Version")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("VERSION");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasFilter("IsDeleted = 0");

                    b.ToTable("THEMES");
                });

            modelBuilder.Entity("QuickCode.DemoCms.SiteManagementModule.Domain.Entities.Domain", b =>
                {
                    b.HasOne("QuickCode.DemoCms.SiteManagementModule.Domain.Entities.Site", "Site")
                        .WithMany("Domains")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Site");
                });

            modelBuilder.Entity("QuickCode.DemoCms.SiteManagementModule.Domain.Entities.NavigationItem", b =>
                {
                    b.HasOne("QuickCode.DemoCms.SiteManagementModule.Domain.Entities.NavigationMenu", "NavigationMenu")
                        .WithMany("NavigationItems")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuickCode.DemoCms.SiteManagementModule.Domain.Entities.NavigationItem", "ParentItem")
                        .WithMany("NavigationItemParentItem")
                        .HasForeignKey("ParentItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NavigationMenu");

                    b.Navigation("ParentItem");
                });

            modelBuilder.Entity("QuickCode.DemoCms.SiteManagementModule.Domain.Entities.NavigationMenu", b =>
                {
                    b.HasOne("QuickCode.DemoCms.SiteManagementModule.Domain.Entities.Site", "Site")
                        .WithMany("NavigationMenus")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Site");
                });

            modelBuilder.Entity("QuickCode.DemoCms.SiteManagementModule.Domain.Entities.Site", b =>
                {
                    b.HasOne("QuickCode.DemoCms.SiteManagementModule.Domain.Entities.Theme", "Theme")
                        .WithMany("Sites")
                        .HasForeignKey("ThemeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Theme");
                });

            modelBuilder.Entity("QuickCode.DemoCms.SiteManagementModule.Domain.Entities.SiteLanguage", b =>
                {
                    b.HasOne("QuickCode.DemoCms.SiteManagementModule.Domain.Entities.Site", "Site")
                        .WithMany("SiteLanguages")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Site");
                });

            modelBuilder.Entity("QuickCode.DemoCms.SiteManagementModule.Domain.Entities.SiteSetting", b =>
                {
                    b.HasOne("QuickCode.DemoCms.SiteManagementModule.Domain.Entities.Site", "Site")
                        .WithMany("SiteSettings")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Site");
                });

            modelBuilder.Entity("QuickCode.DemoCms.SiteManagementModule.Domain.Entities.Template", b =>
                {
                    b.HasOne("QuickCode.DemoCms.SiteManagementModule.Domain.Entities.Theme", "Theme")
                        .WithMany("Templates")
                        .HasForeignKey("ThemeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Theme");
                });

            modelBuilder.Entity("QuickCode.DemoCms.SiteManagementModule.Domain.Entities.NavigationItem", b =>
                {
                    b.Navigation("NavigationItemParentItem");
                });

            modelBuilder.Entity("QuickCode.DemoCms.SiteManagementModule.Domain.Entities.NavigationMenu", b =>
                {
                    b.Navigation("NavigationItems");
                });

            modelBuilder.Entity("QuickCode.DemoCms.SiteManagementModule.Domain.Entities.Site", b =>
                {
                    b.Navigation("Domains");

                    b.Navigation("NavigationMenus");

                    b.Navigation("SiteLanguages");

                    b.Navigation("SiteSettings");
                });

            modelBuilder.Entity("QuickCode.DemoCms.SiteManagementModule.Domain.Entities.Theme", b =>
                {
                    b.Navigation("Sites");

                    b.Navigation("Templates");
                });
#pragma warning restore 612, 618
        }
    }
}
