//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoCms.Common.Models;
using QuickCode.DemoCms.ContentManagementModule.Domain.Entities;
using QuickCode.DemoCms.ContentManagementModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.DemoCms.Common;
using QuickCode.DemoCms.Common.Extensions;
using QuickCode.DemoCms.Common.Helpers;
using QuickCode.DemoCms.ContentManagementModule.Persistence.Contexts;
using QuickCode.DemoCms.ContentManagementModule.Application.Dtos.ContentTag;
using QuickCode.DemoCms.ContentManagementModule.Application.Mappings;
using QuickCode.DemoCms.ContentManagementModule.Persistence.Sql;
using QuickCode.DemoCms.ContentManagementModule.Domain.Enums;

namespace QuickCode.DemoCms.ContentManagementModule.Persistence.Repositories
{
    public partial class ContentTagRepository : BaseRepository, IContentTagRepository
    {
        public async Task<RepoResponse<List<GetTagsForContentResponseDto>>> GetTagsForContentAsync(ContentKind contentTagContentTypeKind, int contentTagContentId)
        {
            return await ExecuteWithExceptionHandling("GetTagsForContent", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.ContentTag.Query.GetTagsForContent);
                var parameters = new
                {
                    PRM_CONTENT_TAG_CONTENT_TYPE_KIND = contentTagContentTypeKind,
                    PRM_CONTENT_TAG_CONTENT_ID = contentTagContentId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetTagsForContentResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in ContentTag");
            });
        }

        public async Task<RepoResponse<List<GetContentForTagResponseDto>>> GetContentForTagAsync(int contentTagTagId, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling("GetContentForTag", async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetContentForTagResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.ContentTag.Query.GetContentForTag);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_CONTENT_TAG_TAG_ID = contentTagTagId,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    using var connection = await GetOpenConnectionAsync(_readContext);
                    var values = await connection.QueryAsync<GetContentForTagResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in ContentTag");
                }
            });
        }
    }
}