SELECT RF.[ID], RF.[FILENAME], RF.[STATUS], RF.[PROCESSED_DATE] 
FROM [RESOURCE_FILES] RF 
WHERE RF.[IsDeleted] = 0 
	AND RF.[LANGUAGE_ID] = @PRM_RESOURCE_FILE_LANGUAGE_ID 
ORDER BY RF.[UPLOADED_DATE] DESC 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 