SELECT RF.[ID], RF.[FILENAME], RF.[FORMAT], RF.[LANGUAGE_ID], RF.[UPLOADED_DATE] 
FROM [RESOURCE_FILES] RF 
WHERE RF.[IsDeleted] = 0 
	AND RF.[STATUS] = @PRM_RESOURCE_FILE_STATUS 
ORDER BY RF.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 