SELECT CT.[CONTENT_TYPE_KIND], CT.[CONTENT_ID] 
FROM [CONTENT_TAGS] CT 
WHERE CT.[TAG_ID] = @PRM_CONTENT_TAG_TAG_ID 
ORDER BY CT.[CONTENT_TYPE_KIND], CT.[CONTENT_ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 