SELECT A.[ID], A.[FILENAME], A.[MIME_TYPE], A.[KIND] 
FROM [ASSETS] A 
WHERE A.[IsDeleted] = 0 
	AND A.[FOLDER_ID] = @PRM_ASSET_FOLDER_ID 
ORDER BY A.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 