SELECT A.[ID], A.[FILENAME], A.[MIME_TYPE], A.[FILE_SIZE_BYTES] 
FROM [ASSETS] A 
WHERE A.[IsDeleted] = 0 
	AND A.[KIND] = @PRM_ASSET_KIND 
ORDER BY A.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 