SELECT A.[ID], A.[FILENAME], A.[MIME_TYPE], A.[KIND] 
FROM [ASSETS] A 
WHERE A.[IsDeleted] = 0 
	AND A.[FILENAME] LIKE '%' + @PRM_ASSET_FILENAME + '%' 
ORDER BY A.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 