//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoCms.Common.Models;
using QuickCode.DemoCms.SiteManagementModule.Domain.Entities;
using QuickCode.DemoCms.SiteManagementModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.DemoCms.Common;
using QuickCode.DemoCms.Common.Extensions;
using QuickCode.DemoCms.Common.Helpers;
using QuickCode.DemoCms.SiteManagementModule.Persistence.Contexts;
using QuickCode.DemoCms.SiteManagementModule.Application.Dtos.NavigationMenu;
using QuickCode.DemoCms.SiteManagementModule.Application.Mappings;
using QuickCode.DemoCms.SiteManagementModule.Persistence.Sql;
using QuickCode.DemoCms.SiteManagementModule.Domain.Enums;

namespace QuickCode.DemoCms.SiteManagementModule.Persistence.Repositories
{
    public partial class NavigationMenuRepository : BaseRepository, INavigationMenuRepository
    {
        public async Task<RepoResponse<List<GetBySiteIdResponseDto>>> GetBySiteIdAsync(int navigationMenuSiteId, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling("GetBySiteId", async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetBySiteIdResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.NavigationMenu.Query.GetBySiteId);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_NAVIGATION_MENU_SITE_ID = navigationMenuSiteId,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    using var connection = await GetOpenConnectionAsync(_readContext);
                    var values = await connection.QueryAsync<GetBySiteIdResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in NavigationMenu");
                }
            });
        }

        public async Task<RepoResponse<GetByLocationResponseDto>> GetByLocationAsync(int navigationMenuSiteId, string navigationMenuLocationKey)
        {
            return await ExecuteWithExceptionHandling("GetByLocation", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.NavigationMenu.Query.GetByLocation);
                var parameters = new
                {
                    PRM_NAVIGATION_MENU_SITE_ID = navigationMenuSiteId,
                    PRM_NAVIGATION_MENU_LOCATION_KEY = navigationMenuLocationKey
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<GetByLocationResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in NavigationMenu");
            });
        }
    }
}