//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoCms.Common.Models;
using QuickCode.DemoCms.AssetManagementModule.Domain.Entities;
using QuickCode.DemoCms.AssetManagementModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.DemoCms.Common;
using QuickCode.DemoCms.Common.Extensions;
using QuickCode.DemoCms.Common.Helpers;
using QuickCode.DemoCms.AssetManagementModule.Persistence.Contexts;
using QuickCode.DemoCms.AssetManagementModule.Application.Dtos.AssetRendition;
using QuickCode.DemoCms.AssetManagementModule.Application.Mappings;
using QuickCode.DemoCms.AssetManagementModule.Persistence.Sql;
using QuickCode.DemoCms.AssetManagementModule.Domain.Enums;

namespace QuickCode.DemoCms.AssetManagementModule.Persistence.Repositories
{
    public partial class AssetRenditionRepository : BaseRepository, IAssetRenditionRepository
    {
        public async Task<RepoResponse<List<GetRenditionsForAssetResponseDto>>> GetRenditionsForAssetAsync(int assetRenditionOriginalAssetId, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling("GetRenditionsForAsset", async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetRenditionsForAssetResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.AssetRendition.Query.GetRenditionsForAsset);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_ASSET_RENDITION_ORIGINAL_ASSET_ID = assetRenditionOriginalAssetId,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    using var connection = await GetOpenConnectionAsync(_readContext);
                    var values = await connection.QueryAsync<GetRenditionsForAssetResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in AssetRendition");
                }
            });
        }

        public async Task<RepoResponse<GetRenditionByNameResponseDto>> GetRenditionByNameAsync(int assetRenditionOriginalAssetId, string assetRenditionName)
        {
            return await ExecuteWithExceptionHandling("GetRenditionByName", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.AssetRendition.Query.GetRenditionByName);
                var parameters = new
                {
                    PRM_ASSET_RENDITION_ORIGINAL_ASSET_ID = assetRenditionOriginalAssetId,
                    PRM_ASSET_RENDITION_NAME = assetRenditionName
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<GetRenditionByNameResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in AssetRendition");
            });
        }
    }
}