//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoCms.Common.Models;
using QuickCode.DemoCms.ContentManagementModule.Domain.Entities;
using QuickCode.DemoCms.ContentManagementModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.DemoCms.Common;
using QuickCode.DemoCms.Common.Extensions;
using QuickCode.DemoCms.Common.Helpers;
using QuickCode.DemoCms.ContentManagementModule.Persistence.Contexts;
using QuickCode.DemoCms.ContentManagementModule.Application.Dtos.ContentType;
using QuickCode.DemoCms.ContentManagementModule.Application.Mappings;
using QuickCode.DemoCms.ContentManagementModule.Persistence.Sql;
using QuickCode.DemoCms.ContentManagementModule.Domain.Enums;

namespace QuickCode.DemoCms.ContentManagementModule.Persistence.Repositories
{
    public partial class ContentTypeRepository : BaseRepository, IContentTypeRepository
    {
        public async Task<RepoResponse<List<GetActiveResponseDto>>> GetActiveAsync(bool contentTypeIsActive, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling("GetActive", async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetActiveResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.ContentType.Query.GetActive);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_CONTENT_TYPE_IS_ACTIVE = contentTypeIsActive,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    using var connection = await GetOpenConnectionAsync(_readContext);
                    var values = await connection.QueryAsync<GetActiveResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in ContentType");
                }
            });
        }

        public async Task<RepoResponse<List<GetByKindResponseDto>>> GetByKindAsync(ContentKind contentTypeKind, bool contentTypeIsActive, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling("GetByKind", async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetByKindResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.ContentType.Query.GetByKind);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_CONTENT_TYPE_KIND = contentTypeKind,
                        PRM_CONTENT_TYPE_IS_ACTIVE = contentTypeIsActive,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    using var connection = await GetOpenConnectionAsync(_readContext);
                    var values = await connection.QueryAsync<GetByKindResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in ContentType");
                }
            });
        }

        public async Task<RepoResponse<List<SearchByNameResponseDto>>> SearchByNameAsync(string contentTypeName, bool contentTypeIsActive, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling("SearchByName", async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<SearchByNameResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.ContentType.Query.SearchByName);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_CONTENT_TYPE_NAME = contentTypeName,
                        PRM_CONTENT_TYPE_IS_ACTIVE = contentTypeIsActive,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    using var connection = await GetOpenConnectionAsync(_readContext);
                    var values = await connection.QueryAsync<SearchByNameResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in ContentType");
                }
            });
        }

        public async Task<RepoResponse<GetByApiKeyResponseDto>> GetByApiKeyAsync(string contentTypeApiKey)
        {
            return await ExecuteWithExceptionHandling("GetByApiKey", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.ContentType.Query.GetByApiKey);
                var parameters = new
                {
                    PRM_CONTENT_TYPE_API_KEY = contentTypeApiKey
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<GetByApiKeyResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in ContentType");
            });
        }
    }
}