SELECT AM.[ASSET_ID] 
FROM [ASSET_METADATAS] AM 
WHERE AM.[IsDeleted] = 0 
	AND AM.[KEY] = @PRM_ASSET_METADATA_KEY 
	AND AM.[VALUE] = @PRM_ASSET_METADATA_VALUE 
ORDER BY 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 