SELECT N.[ID], N.[NAME], N.[DESCRIPTION] 
FROM [NAMESPACES] N 
WHERE N.[IsDeleted] = 0 
	AND N.[IS_ACTIVE] = @PRM_NAMESPACE_IS_ACTIVE 
ORDER BY N.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 