SELECT N.[ID], N.[NAME], N.[DESCRIPTION] 
FROM [NAMESPACES] N 
WHERE N.[IsDeleted] = 0 
	AND N.[NAME] LIKE '%' + @PRM_NAMESPACE_NAME + '%' 
ORDER BY N.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 