//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.DemoCms.ContentManagementModule.Application.Dtos.BlockTranslation;
using QuickCode.DemoCms.ContentManagementModule.Domain.Entities;
using QuickCode.DemoCms.ContentManagementModule.Domain.Enums;

namespace QuickCode.DemoCms.ContentManagementModule.Application.Mappings
{
    public static class BlockTranslationMappings
    {
        public static List<BlockTranslationDto> ToDto(this IEnumerable<BlockTranslation> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static BlockTranslationDto ToDto(this BlockTranslation model)
        {
            return new BlockTranslationDto
            {
                Id = model.Id,
                BlockId = model.BlockId,
                LanguageCode = model.LanguageCode,
                Content = model.Content
            };
        }

        public static BlockTranslation ToEntity(this BlockTranslationDto model)
        {
            return new BlockTranslation
            {
                Id = model.Id,
                BlockId = model.BlockId,
                LanguageCode = model.LanguageCode,
                Content = model.Content
            };
        }
    }
}