//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.DemoCms.ContentManagementModule.Application.Dtos.ContentBlock;
using QuickCode.DemoCms.ContentManagementModule.Domain.Entities;
using QuickCode.DemoCms.ContentManagementModule.Domain.Enums;

namespace QuickCode.DemoCms.ContentManagementModule.Application.Mappings
{
    public static class ContentBlockMappings
    {
        public static List<ContentBlockDto> ToDto(this IEnumerable<ContentBlock> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static ContentBlockDto ToDto(this ContentBlock model)
        {
            return new ContentBlockDto
            {
                Id = model.Id,
                ContentTypeId = model.ContentTypeId,
                Key = model.Key,
                Description = model.Description,
                IsActive = model.IsActive
            };
        }

        public static ContentBlock ToEntity(this ContentBlockDto model)
        {
            return new ContentBlock
            {
                Id = model.Id,
                ContentTypeId = model.ContentTypeId,
                Key = model.Key,
                Description = model.Description,
                IsActive = model.IsActive
            };
        }
    }
}