//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.DemoCms.ContentManagementModule.Application.Dtos.ContentType;
using ContentTypeEntity = QuickCode.DemoCms.ContentManagementModule.Domain.Entities.ContentType;
using QuickCode.DemoCms.ContentManagementModule.Domain.Enums;

namespace QuickCode.DemoCms.ContentManagementModule.Application.Mappings
{
    public static class ContentTypeMappings
    {
        public static List<ContentTypeDto> ToDto(this IEnumerable<ContentTypeEntity> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static ContentTypeDto ToDto(this ContentTypeEntity model)
        {
            return new ContentTypeDto
            {
                Id = model.Id,
                Name = model.Name,
                ApiKey = model.ApiKey,
                Kind = model.Kind,
                Description = model.Description,
                IsActive = model.IsActive
            };
        }

        public static ContentTypeEntity ToEntity(this ContentTypeDto model)
        {
            return new ContentTypeEntity
            {
                Id = model.Id,
                Name = model.Name,
                ApiKey = model.ApiKey,
                Kind = model.Kind,
                Description = model.Description,
                IsActive = model.IsActive
            };
        }
    }
}