//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.DemoCms.ContentManagementModule.Application.Dtos.ContentVersion;
using QuickCode.DemoCms.ContentManagementModule.Domain.Entities;
using QuickCode.DemoCms.ContentManagementModule.Domain.Enums;

namespace QuickCode.DemoCms.ContentManagementModule.Application.Mappings
{
    public static class ContentVersionMappings
    {
        public static List<ContentVersionDto> ToDto(this IEnumerable<ContentVersion> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static ContentVersionDto ToDto(this ContentVersion model)
        {
            return new ContentVersionDto
            {
                Id = model.Id,
                ContentTypeKind = model.ContentTypeKind,
                ContentId = model.ContentId,
                TranslationId = model.TranslationId,
                VersionNumber = model.VersionNumber,
                ContentSnapshot = model.ContentSnapshot,
                CreatedByUserId = model.CreatedByUserId,
                CreatedDate = model.CreatedDate
            };
        }

        public static ContentVersion ToEntity(this ContentVersionDto model)
        {
            return new ContentVersion
            {
                Id = model.Id,
                ContentTypeKind = model.ContentTypeKind,
                ContentId = model.ContentId,
                TranslationId = model.TranslationId,
                VersionNumber = model.VersionNumber,
                ContentSnapshot = model.ContentSnapshot,
                CreatedByUserId = model.CreatedByUserId,
                CreatedDate = model.CreatedDate
            };
        }
    }
}