//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.DemoCms.ContentManagementModule.Application.Dtos.Page;
using QuickCode.DemoCms.ContentManagementModule.Domain.Entities;
using QuickCode.DemoCms.ContentManagementModule.Domain.Enums;

namespace QuickCode.DemoCms.ContentManagementModule.Application.Mappings
{
    public static class PageMappings
    {
        public static List<PageDto> ToDto(this IEnumerable<Page> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static PageDto ToDto(this Page model)
        {
            return new PageDto
            {
                Id = model.Id,
                ContentTypeId = model.ContentTypeId,
                ParentPageId = model.ParentPageId,
                Status = model.Status,
                PublishDate = model.PublishDate,
                CreatedDate = model.CreatedDate,
                UpdatedDate = model.UpdatedDate
            };
        }

        public static Page ToEntity(this PageDto model)
        {
            return new Page
            {
                Id = model.Id,
                ContentTypeId = model.ContentTypeId,
                ParentPageId = model.ParentPageId,
                Status = model.Status,
                PublishDate = model.PublishDate,
                CreatedDate = model.CreatedDate,
                UpdatedDate = model.UpdatedDate
            };
        }
    }
}