//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.DemoCms.ContentManagementModule.Application.Dtos.Post;
using PostEntity = QuickCode.DemoCms.ContentManagementModule.Domain.Entities.Post;
using QuickCode.DemoCms.ContentManagementModule.Domain.Enums;

namespace QuickCode.DemoCms.ContentManagementModule.Application.Mappings
{
    public static class PostMappings
    {
        public static List<PostDto> ToDto(this IEnumerable<PostEntity> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static PostDto ToDto(this PostEntity model)
        {
            return new PostDto
            {
                Id = model.Id,
                ContentTypeId = model.ContentTypeId,
                AuthorId = model.AuthorId,
                Status = model.Status,
                PublishDate = model.PublishDate,
                CreatedDate = model.CreatedDate,
                UpdatedDate = model.UpdatedDate
            };
        }

        public static PostEntity ToEntity(this PostDto model)
        {
            return new PostEntity
            {
                Id = model.Id,
                ContentTypeId = model.ContentTypeId,
                AuthorId = model.AuthorId,
                Status = model.Status,
                PublishDate = model.PublishDate,
                CreatedDate = model.CreatedDate,
                UpdatedDate = model.UpdatedDate
            };
        }
    }
}