//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.DemoCms.ContentManagementModule.Application.Dtos.PostTranslation;
using QuickCode.DemoCms.ContentManagementModule.Domain.Entities;
using QuickCode.DemoCms.ContentManagementModule.Domain.Enums;

namespace QuickCode.DemoCms.ContentManagementModule.Application.Mappings
{
    public static class PostTranslationMappings
    {
        public static List<PostTranslationDto> ToDto(this IEnumerable<PostTranslation> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static PostTranslationDto ToDto(this PostTranslation model)
        {
            return new PostTranslationDto
            {
                Id = model.Id,
                PostId = model.PostId,
                LanguageCode = model.LanguageCode,
                Title = model.Title,
                Slug = model.Slug,
                Excerpt = model.Excerpt,
                Content = model.Content
            };
        }

        public static PostTranslation ToEntity(this PostTranslationDto model)
        {
            return new PostTranslation
            {
                Id = model.Id,
                PostId = model.PostId,
                LanguageCode = model.LanguageCode,
                Title = model.Title,
                Slug = model.Slug,
                Excerpt = model.Excerpt,
                Content = model.Content
            };
        }
    }
}