//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoCms.Common.Models;
using QuickCode.DemoCms.LocalizationModule.Domain.Entities;
using QuickCode.DemoCms.LocalizationModule.Application.Dtos.LanguageFallback;
using System.Threading.Tasks;
using QuickCode.DemoCms.LocalizationModule.Domain.Enums;

namespace QuickCode.DemoCms.LocalizationModule.Application.Interfaces.Repositories
{
    public partial interface ILanguageFallbackRepository : IBaseRepository<LanguageFallbackDto>
    {
        Task<RepoResponse<LanguageFallbackDto>> GetByPkAsync(int languageId, int fallbackLanguageId);
        Task<RepoResponse<List<GetFallbacksForLanguageResponseDto>>> GetFallbacksForLanguageAsync(int languageFallbackLanguageId);
        Task<RepoResponse<int>> RemoveFallbackAsync(int languageFallbackLanguageId, int languageFallbackFallbackLanguageId);
    }
}