//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoCms.Common.Models;
using QuickCode.DemoCms.LocalizationModule.Domain.Entities;
using QuickCode.DemoCms.LocalizationModule.Application.Dtos.ResourceFile;
using System.Threading.Tasks;
using QuickCode.DemoCms.LocalizationModule.Domain.Enums;

namespace QuickCode.DemoCms.LocalizationModule.Application.Interfaces.Repositories
{
    public partial interface IResourceFileRepository : IBaseRepository<ResourceFileDto>
    {
        Task<RepoResponse<ResourceFileDto>> GetByPkAsync(int id);
        Task<RepoResponse<List<GetPendingImportsResponseDto>>> GetPendingImportsAsync(string resourceFileStatus, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetImportHistoryResponseDto>>> GetImportHistoryAsync(int resourceFileLanguageId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<int>> MarkAsProcessedAsync(int resourceFileId, MarkAsProcessedRequestDto updateRequest);
        Task<RepoResponse<int>> MarkAsFailedAsync(int resourceFileId, MarkAsFailedRequestDto updateRequest);
    }
}