//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoCms.Common.Models;
using QuickCode.DemoCms.LocalizationModule.Domain.Entities;
using QuickCode.DemoCms.LocalizationModule.Application.Dtos.TranslationValue;
using System.Threading.Tasks;
using QuickCode.DemoCms.LocalizationModule.Domain.Enums;

namespace QuickCode.DemoCms.LocalizationModule.Application.Interfaces.Repositories
{
    public partial interface ITranslationValueRepository : IBaseRepository<TranslationValueDto>
    {
        Task<RepoResponse<TranslationValueDto>> GetByPkAsync(int id);
        Task<RepoResponse<GetByKeyAndLanguageResponseDto>> GetByKeyAndLanguageAsync(int translationValueKeyId, int translationValueLanguageId);
        Task<RepoResponse<List<GetTranslationsForLanguageAndNamespaceResponseDto>>> GetTranslationsForLanguageAndNamespaceAsync(int translationValuesLanguageId, int translationKeysNamespaceId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<int>> BulkUpsertAsync(int translationValueKeyId, int translationValueLanguageId, BulkUpsertRequestDto updateRequest);
    }
}