//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoCms.Common.Models;
using QuickCode.DemoCms.LocalizationModule.Domain.Entities;
using QuickCode.DemoCms.LocalizationModule.Application.Dtos.TranslationKey;
using System.Threading.Tasks;
using QuickCode.DemoCms.LocalizationModule.Domain.Enums;

namespace QuickCode.DemoCms.LocalizationModule.Application.Interfaces.Repositories
{
    public partial interface ITranslationKeyRepository : IBaseRepository<TranslationKeyDto>
    {
        Task<RepoResponse<TranslationKeyDto>> GetByPkAsync(int id);
        Task<RepoResponse<List<GetByNamespaceResponseDto>>> GetByNamespaceAsync(int translationKeyNamespaceId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<SearchByKeyResponseDto>>> SearchByKeyAsync(string translationKeyKey, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetUntranslatedKeysForLanguageResponseDto>>> GetUntranslatedKeysForLanguageAsync(int translationKeyNamespaceId, int? pageNumber = null, int? pageSize = null);
    }
}