SELECT AF.[ID], AF.[NAME], AF.[PATH] 
FROM [ASSET_FOLDERS] AF 
WHERE AF.[IsDeleted] = 0 
	AND AF.[PARENT_FOLDER_ID] = @PRM_ASSET_FOLDER_PARENT_FOLDER_ID 
ORDER BY AF.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 