SELECT AF.[ID], AF.[NAME], AF.[PATH] 
FROM [ASSET_FOLDERS] AF 
WHERE AF.[IsDeleted] = 0 
	AND AF.[NAME] LIKE '%' + @PRM_ASSET_FOLDER_NAME + '%' 
ORDER BY AF.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 