SELECT T.[ID], T.[NAME], T.[KEY], T.[DESCRIPTION] 
FROM [TEMPLATES] T 
WHERE T.[IsDeleted] = 0 
	AND T.[THEME_ID] = @PRM_TEMPLATE_THEME_ID 
ORDER BY T.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 