// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuickCode.DemoCms.LocalizationModule.Persistence.Contexts;

#nullable disable

namespace QuickCode.DemoCms.LocalizationModule.Persistence.Migrations
{
    [DbContext(typeof(WriteDbContext))]
    partial class WriteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuickCode.DemoCms.LocalizationModule.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<string>("Action")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ACTION");

                    b.Property<string>("ChangeSummary")
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CHANGE_SUMMARY");

                    b.Property<string>("ChangedColumns")
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CHANGED_COLUMNS");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CORRELATION_ID");

                    b.Property<string>("EntityId")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("ENTITY_ID");

                    b.Property<string>("EntityName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("ENTITY_NAME");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ERROR_MESSAGE");

                    b.Property<string>("Hash")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("HASH");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("IP_ADDRESS");

                    b.Property<bool>("IsChanged")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IS_CHANGED");

                    b.Property<bool>("IsSuccess")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IS_SUCCESS");

                    b.Property<string>("NewValues")
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NEW_VALUES");

                    b.Property<string>("OldValues")
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("OLD_VALUES");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2")
                        .HasColumnName("TIMESTAMP");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("USER_AGENT");

                    b.Property<string>("UserGroup")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("USER_GROUP");

                    b.Property<string>("UserId")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("USER_ID");

                    b.Property<string>("UserName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("USER_NAME");

                    b.HasKey("Id");

                    b.ToTable("AUDIT_LOGS");
                });

            modelBuilder.Entity("QuickCode.DemoCms.LocalizationModule.Domain.Entities.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CODE");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedOnUtc");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("IS_ACTIVE");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IS_DEFAULT");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<string>("Name")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("NAME");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasFilter("IsDeleted = 0");

                    b.ToTable("LANGUAGES");
                });

            modelBuilder.Entity("QuickCode.DemoCms.LocalizationModule.Domain.Entities.LanguageFallback", b =>
                {
                    b.Property<int>("LanguageId")
                        .HasColumnType("int")
                        .HasColumnName("LANGUAGE_ID");

                    b.Property<int>("FallbackLanguageId")
                        .HasColumnType("int")
                        .HasColumnName("FALLBACK_LANGUAGE_ID");

                    b.Property<int>("Priority")
                        .HasColumnType("int")
                        .HasColumnName("PRIORITY");

                    b.HasKey("LanguageId", "FallbackLanguageId");

                    b.HasIndex("FallbackLanguageId");

                    b.ToTable("LANGUAGE_FALLBACKS");
                });

            modelBuilder.Entity("QuickCode.DemoCms.LocalizationModule.Domain.Entities.Namespace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedOnUtc");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("IS_ACTIVE");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NAME");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasFilter("IsDeleted = 0");

                    b.ToTable("NAMESPACES");
                });

            modelBuilder.Entity("QuickCode.DemoCms.LocalizationModule.Domain.Entities.ResourceFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedOnUtc");

                    b.Property<string>("Filename")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("FILENAME");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("FORMAT");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int")
                        .HasColumnName("LANGUAGE_ID");

                    b.Property<DateTime>("ProcessedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("PROCESSED_DATE");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("STATUS");

                    b.Property<int>("UploadedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("UPLOADED_BY_USER_ID");

                    b.Property<DateTime>("UploadedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UPLOADED_DATE");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("LanguageId");

                    b.ToTable("RESOURCE_FILES");
                });

            modelBuilder.Entity("QuickCode.DemoCms.LocalizationModule.Domain.Entities.TranslationKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATED_DATE");

                    b.Property<string>("DefaultValue")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("DEFAULT_VALUE");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedOnUtc");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<string>("Key")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("KEY");

                    b.Property<int>("NamespaceId")
                        .HasColumnType("int")
                        .HasColumnName("NAMESPACE_ID");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("NamespaceId");

                    b.ToTable("TRANSLATION_KEYS");
                });

            modelBuilder.Entity("QuickCode.DemoCms.LocalizationModule.Domain.Entities.TranslationValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedOnUtc");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<int>("KeyId")
                        .HasColumnType("int")
                        .HasColumnName("KEY_ID");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int")
                        .HasColumnName("LANGUAGE_ID");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UPDATED_DATE");

                    b.Property<string>("Value")
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("VALUE");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("KeyId");

                    b.HasIndex("LanguageId");

                    b.ToTable("TRANSLATION_VALUES");
                });

            modelBuilder.Entity("QuickCode.DemoCms.LocalizationModule.Domain.Entities.LanguageFallback", b =>
                {
                    b.HasOne("QuickCode.DemoCms.LocalizationModule.Domain.Entities.Language", "FallbackLanguage")
                        .WithMany("LanguageFallbackFallbackLanguage")
                        .HasForeignKey("FallbackLanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuickCode.DemoCms.LocalizationModule.Domain.Entities.Language", "Language")
                        .WithMany("LanguageFallbackLanguage")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FallbackLanguage");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("QuickCode.DemoCms.LocalizationModule.Domain.Entities.ResourceFile", b =>
                {
                    b.HasOne("QuickCode.DemoCms.LocalizationModule.Domain.Entities.Language", "Language")
                        .WithMany("ResourceFiles")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("QuickCode.DemoCms.LocalizationModule.Domain.Entities.TranslationKey", b =>
                {
                    b.HasOne("QuickCode.DemoCms.LocalizationModule.Domain.Entities.Namespace", "Namespace")
                        .WithMany("TranslationKeys")
                        .HasForeignKey("NamespaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Namespace");
                });

            modelBuilder.Entity("QuickCode.DemoCms.LocalizationModule.Domain.Entities.TranslationValue", b =>
                {
                    b.HasOne("QuickCode.DemoCms.LocalizationModule.Domain.Entities.TranslationKey", "TranslationKey")
                        .WithMany("TranslationValues")
                        .HasForeignKey("KeyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuickCode.DemoCms.LocalizationModule.Domain.Entities.Language", "Language")
                        .WithMany("TranslationValues")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("TranslationKey");
                });

            modelBuilder.Entity("QuickCode.DemoCms.LocalizationModule.Domain.Entities.Language", b =>
                {
                    b.Navigation("LanguageFallbackFallbackLanguage");

                    b.Navigation("LanguageFallbackLanguage");

                    b.Navigation("ResourceFiles");

                    b.Navigation("TranslationValues");
                });

            modelBuilder.Entity("QuickCode.DemoCms.LocalizationModule.Domain.Entities.Namespace", b =>
                {
                    b.Navigation("TranslationKeys");
                });

            modelBuilder.Entity("QuickCode.DemoCms.LocalizationModule.Domain.Entities.TranslationKey", b =>
                {
                    b.Navigation("TranslationValues");
                });
#pragma warning restore 612, 618
        }
    }
}
