SELECT TOP 1 SS.[ID], SS.[VALUE], SS.[IS_SECRET] 
FROM [SITE_SETTINGS] SS 
WHERE SS.[IsDeleted] = 0 
	AND SS.[SITE_ID] = @PRM_SITE_SETTING_SITE_ID 
	AND SS.[KEY] = @PRM_SITE_SETTING_KEY 
ORDER BY SS.[ID] 