SELECT NI.[ID], NI.[PARENT_ITEM_ID], NI.[TYPE], NI.[LABEL], NI.[URL], NI.[PAGE_ID], NI.[SORT_ORDER], NI.[IS_VISIBLE] 
FROM [NAVIGATION_ITEMS] NI 
WHERE NI.[IsDeleted] = 0 
	AND NI.[MENU_ID] = @PRM_NAVIGATION_ITEM_MENU_ID 
ORDER BY NI.[SORT_ORDER] ASC 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 