SELECT SP.[ID], SP.[NAME], SP.[TYPE], SP.[IS_DEFAULT] 
FROM [STORAGE_PROVIDERS] SP 
WHERE SP.[IsDeleted] = 0 
	AND SP.[IS_ACTIVE] = @PRM_STORAGE_PROVIDER_IS_ACTIVE 
ORDER BY SP.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 