SELECT TOP 1 SP.[ID], SP.[NAME], SP.[TYPE], SP.[CONFIGURATION] 
FROM [STORAGE_PROVIDERS] SP 
WHERE SP.[IsDeleted] = 0 
	AND SP.[IS_DEFAULT] = @PRM_STORAGE_PROVIDER_IS_DEFAULT 
	AND SP.[IS_ACTIVE] = @PRM_STORAGE_PROVIDER_IS_ACTIVE 
ORDER BY SP.[ID] 