//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.DemoCms.AssetManagementModule.Application.Dtos.AssetMetadata;
using AssetMetadataEntity = QuickCode.DemoCms.AssetManagementModule.Domain.Entities.AssetMetadata;
using QuickCode.DemoCms.AssetManagementModule.Domain.Enums;

namespace QuickCode.DemoCms.AssetManagementModule.Application.Mappings
{
    public static class AssetMetadataMappings
    {
        public static List<AssetMetadataDto> ToDto(this IEnumerable<AssetMetadataEntity> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static AssetMetadataDto ToDto(this AssetMetadataEntity model)
        {
            return new AssetMetadataDto
            {
                Id = model.Id,
                AssetId = model.AssetId,
                Key = model.Key,
                Value = model.Value
            };
        }

        public static AssetMetadataEntity ToEntity(this AssetMetadataDto model)
        {
            return new AssetMetadataEntity
            {
                Id = model.Id,
                AssetId = model.AssetId,
                Key = model.Key,
                Value = model.Value
            };
        }
    }
}