//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.DemoCms.AssetManagementModule.Application.Dtos.AssetFolder;
using QuickCode.DemoCms.AssetManagementModule.Domain.Entities;
using QuickCode.DemoCms.AssetManagementModule.Domain.Enums;

namespace QuickCode.DemoCms.AssetManagementModule.Application.Mappings
{
    public static class AssetFolderMappings
    {
        public static List<AssetFolderDto> ToDto(this IEnumerable<AssetFolder> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static AssetFolderDto ToDto(this AssetFolder model)
        {
            return new AssetFolderDto
            {
                Id = model.Id,
                ParentFolderId = model.ParentFolderId,
                Name = model.Name,
                Path = model.Path,
                CreatedDate = model.CreatedDate
            };
        }

        public static AssetFolder ToEntity(this AssetFolderDto model)
        {
            return new AssetFolder
            {
                Id = model.Id,
                ParentFolderId = model.ParentFolderId,
                Name = model.Name,
                Path = model.Path,
                CreatedDate = model.CreatedDate
            };
        }
    }
}