//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.DemoCms.AssetManagementModule.Application.Dtos.AssetRendition;
using AssetRenditionEntity = QuickCode.DemoCms.AssetManagementModule.Domain.Entities.AssetRendition;
using QuickCode.DemoCms.AssetManagementModule.Domain.Enums;

namespace QuickCode.DemoCms.AssetManagementModule.Application.Mappings
{
    public static class AssetRenditionMappings
    {
        public static List<AssetRenditionDto> ToDto(this IEnumerable<AssetRenditionEntity> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static AssetRenditionDto ToDto(this AssetRenditionEntity model)
        {
            return new AssetRenditionDto
            {
                Id = model.Id,
                OriginalAssetId = model.OriginalAssetId,
                Name = model.Name,
                Width = model.Width,
                Height = model.Height,
                FileSizeBytes = model.FileSizeBytes,
                MimeType = model.MimeType,
                StoragePath = model.StoragePath
            };
        }

        public static AssetRenditionEntity ToEntity(this AssetRenditionDto model)
        {
            return new AssetRenditionEntity
            {
                Id = model.Id,
                OriginalAssetId = model.OriginalAssetId,
                Name = model.Name,
                Width = model.Width,
                Height = model.Height,
                FileSizeBytes = model.FileSizeBytes,
                MimeType = model.MimeType,
                StoragePath = model.StoragePath
            };
        }
    }
}