//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.DemoCms.AssetManagementModule.Application.Dtos.AssetTranslation;
using AssetTranslationEntity = QuickCode.DemoCms.AssetManagementModule.Domain.Entities.AssetTranslation;
using QuickCode.DemoCms.AssetManagementModule.Domain.Enums;

namespace QuickCode.DemoCms.AssetManagementModule.Application.Mappings
{
    public static class AssetTranslationMappings
    {
        public static List<AssetTranslationDto> ToDto(this IEnumerable<AssetTranslationEntity> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static AssetTranslationDto ToDto(this AssetTranslationEntity model)
        {
            return new AssetTranslationDto
            {
                Id = model.Id,
                AssetId = model.AssetId,
                LanguageCode = model.LanguageCode,
                Title = model.Title,
                AltText = model.AltText,
                Caption = model.Caption
            };
        }

        public static AssetTranslationEntity ToEntity(this AssetTranslationDto model)
        {
            return new AssetTranslationEntity
            {
                Id = model.Id,
                AssetId = model.AssetId,
                LanguageCode = model.LanguageCode,
                Title = model.Title,
                AltText = model.AltText,
                Caption = model.Caption
            };
        }
    }
}