//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.DemoCms.AssetManagementModule.Application.Dtos.Asset;
using QuickCode.DemoCms.AssetManagementModule.Domain.Entities;
using QuickCode.DemoCms.AssetManagementModule.Domain.Enums;

namespace QuickCode.DemoCms.AssetManagementModule.Application.Mappings
{
    public static class AssetMappings
    {
        public static List<AssetDto> ToDto(this IEnumerable<Asset> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static AssetDto ToDto(this Asset model)
        {
            return new AssetDto
            {
                Id = model.Id,
                FolderId = model.FolderId,
                Filename = model.Filename,
                FileSizeBytes = model.FileSizeBytes,
                MimeType = model.MimeType,
                Kind = model.Kind,
                StorageProviderId = model.StorageProviderId,
                StoragePath = model.StoragePath,
                CreatedDate = model.CreatedDate
            };
        }

        public static Asset ToEntity(this AssetDto model)
        {
            return new Asset
            {
                Id = model.Id,
                FolderId = model.FolderId,
                Filename = model.Filename,
                FileSizeBytes = model.FileSizeBytes,
                MimeType = model.MimeType,
                Kind = model.Kind,
                StorageProviderId = model.StorageProviderId,
                StoragePath = model.StoragePath,
                CreatedDate = model.CreatedDate
            };
        }
    }
}