//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.DemoCms.AssetManagementModule.Application.Dtos.StorageProvider;
using QuickCode.DemoCms.AssetManagementModule.Domain.Entities;
using QuickCode.DemoCms.AssetManagementModule.Domain.Enums;

namespace QuickCode.DemoCms.AssetManagementModule.Application.Mappings
{
    public static class StorageProviderMappings
    {
        public static List<StorageProviderDto> ToDto(this IEnumerable<StorageProvider> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static StorageProviderDto ToDto(this StorageProvider model)
        {
            return new StorageProviderDto
            {
                Id = model.Id,
                Name = model.Name,
                Type = model.Type,
                Configuration = model.Configuration,
                IsDefault = model.IsDefault,
                IsActive = model.IsActive
            };
        }

        public static StorageProvider ToEntity(this StorageProviderDto model)
        {
            return new StorageProvider
            {
                Id = model.Id,
                Name = model.Name,
                Type = model.Type,
                Configuration = model.Configuration,
                IsDefault = model.IsDefault,
                IsActive = model.IsActive
            };
        }
    }
}