SELECT CT.[ID], CT.[NAME], CT.[API_KEY] 
FROM [CONTENT_TYPES] CT 
WHERE CT.[IsDeleted] = 0 
	AND CT.[KIND] = @PRM_CONTENT_TYPE_KIND 
	AND CT.[IS_ACTIVE] = @PRM_CONTENT_TYPE_IS_ACTIVE 
ORDER BY CT.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 