SELECT CT.[ID], CT.[NAME], CT.[API_KEY], CT.[KIND] 
FROM [CONTENT_TYPES] CT 
WHERE CT.[IsDeleted] = 0 
	AND CT.[NAME] LIKE '%' + @PRM_CONTENT_TYPE_NAME + '%' 
	AND CT.[IS_ACTIVE] = @PRM_CONTENT_TYPE_IS_ACTIVE 
ORDER BY CT.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 