//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoCms.Common.Models;
using QuickCode.DemoCms.SiteManagementModule.Domain.Entities;
using QuickCode.DemoCms.SiteManagementModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.DemoCms.Common;
using QuickCode.DemoCms.Common.Extensions;
using QuickCode.DemoCms.Common.Helpers;
using QuickCode.DemoCms.SiteManagementModule.Persistence.Contexts;
using QuickCode.DemoCms.SiteManagementModule.Application.Dtos.Domain;
using QuickCode.DemoCms.SiteManagementModule.Application.Mappings;
using QuickCode.DemoCms.SiteManagementModule.Persistence.Sql;
using QuickCode.DemoCms.SiteManagementModule.Domain.Enums;

namespace QuickCode.DemoCms.SiteManagementModule.Persistence.Repositories
{
    public partial class DomainRepository : BaseRepository, IDomainRepository
    {
        public async Task<RepoResponse<int>> SetAsPrimaryAsync(int domainId, int domainSiteId, SetAsPrimaryRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling("Domain", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Domain.Command.SetAsPrimary);
                var parameters = new
                {
                    PRM_DOMAIN_ID = domainId,
                    PRM_DOMAIN_SITE_ID = domainSiteId
                };
                using var connection = await GetOpenConnectionAsync(_writeContext);
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result, "Success");
            });
        }

        public async Task<RepoResponse<int>> DeactivateAsync(int domainId, DeactivateRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling("Domain", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Domain.Command.Deactivate);
                var parameters = new
                {
                    PRM_DOMAIN_ID = domainId
                };
                using var connection = await GetOpenConnectionAsync(_writeContext);
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result, "Success");
            });
        }
    }
}