SELECT T.[ID], T.[NAME], T.[VERSION], T.[DEVELOPER] 
FROM [THEMES] T 
WHERE T.[IsDeleted] = 0 
	AND T.[IS_ACTIVE] = @PRM_THEME_IS_ACTIVE 
ORDER BY T.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 