//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoCms.Common.Models;
using QuickCode.DemoCms.IdentityModule.Domain.Entities;
using QuickCode.DemoCms.IdentityModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.DemoCms.Common;
using QuickCode.DemoCms.Common.Extensions;
using QuickCode.DemoCms.Common.Helpers;
using QuickCode.DemoCms.IdentityModule.Persistence.Contexts;
using QuickCode.DemoCms.IdentityModule.Application.Dtos.Module;
using QuickCode.DemoCms.IdentityModule.Application.Mappings;
using QuickCode.DemoCms.IdentityModule.Persistence.Sql;
using QuickCode.DemoCms.IdentityModule.Domain.Enums;

namespace QuickCode.DemoCms.IdentityModule.Persistence.Repositories
{
    public partial class ModuleRepository : BaseRepository, IModuleRepository
    {
        public async Task<RepoResponse<bool>> ModuleNameIsExistsAsync(string moduleName)
        {
            return await ExecuteWithExceptionHandling("ModuleNameIsExists", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Module.Query.ModuleNameIsExists);
                var parameters = new
                {
                    PRM_Module_Name = moduleName
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var exists = await connection.ExecuteScalarAsync<bool>(sql, parameters);
                return BuildBoolResponse(exists, $"Not found in Module");
            });
        }
    }
}