//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.DemoCms.SiteManagementModule.Application.Dtos.Domain;
using QuickCode.DemoCms.SiteManagementModule.Domain.Entities;
using QuickCode.DemoCms.SiteManagementModule.Domain.Enums;

namespace QuickCode.DemoCms.SiteManagementModule.Application.Mappings
{
    public static class DomainMappings
    {
        public static List<DomainDto> ToDto(this IEnumerable<Domain> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static DomainDto ToDto(this Domain model)
        {
            return new DomainDto
            {
                Id = model.Id,
                SiteId = model.SiteId,
                Hostname = model.Hostname,
                IsPrimary = model.IsPrimary,
                IsActive = model.IsActive
            };
        }

        public static Domain ToEntity(this DomainDto model)
        {
            return new Domain
            {
                Id = model.Id,
                SiteId = model.SiteId,
                Hostname = model.Hostname,
                IsPrimary = model.IsPrimary,
                IsActive = model.IsActive
            };
        }
    }
}