//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.DemoCms.SiteManagementModule.Application.Dtos.SiteLanguage;
using SiteLanguageEntity = QuickCode.DemoCms.SiteManagementModule.Domain.Entities.SiteLanguage;
using QuickCode.DemoCms.SiteManagementModule.Domain.Enums;

namespace QuickCode.DemoCms.SiteManagementModule.Application.Mappings
{
    public static class SiteLanguageMappings
    {
        public static List<SiteLanguageDto> ToDto(this IEnumerable<SiteLanguageEntity> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static SiteLanguageDto ToDto(this SiteLanguageEntity model)
        {
            return new SiteLanguageDto
            {
                SiteId = model.SiteId,
                LanguageId = model.LanguageId,
                IsEnabled = model.IsEnabled
            };
        }

        public static SiteLanguageEntity ToEntity(this SiteLanguageDto model)
        {
            return new SiteLanguageEntity
            {
                SiteId = model.SiteId,
                LanguageId = model.LanguageId,
                IsEnabled = model.IsEnabled
            };
        }
    }
}