//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.DemoCms.SiteManagementModule.Application.Dtos.Site;
using QuickCode.DemoCms.SiteManagementModule.Domain.Entities;
using QuickCode.DemoCms.SiteManagementModule.Domain.Enums;

namespace QuickCode.DemoCms.SiteManagementModule.Application.Mappings
{
    public static class SiteMappings
    {
        public static List<SiteDto> ToDto(this IEnumerable<Site> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static SiteDto ToDto(this Site model)
        {
            return new SiteDto
            {
                Id = model.Id,
                Name = model.Name,
                DefaultLanguageId = model.DefaultLanguageId,
                ThemeId = model.ThemeId,
                IsActive = model.IsActive,
                CreatedDate = model.CreatedDate
            };
        }

        public static Site ToEntity(this SiteDto model)
        {
            return new Site
            {
                Id = model.Id,
                Name = model.Name,
                DefaultLanguageId = model.DefaultLanguageId,
                ThemeId = model.ThemeId,
                IsActive = model.IsActive,
                CreatedDate = model.CreatedDate
            };
        }
    }
}