//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.DemoCms.SiteManagementModule.Application.Dtos.Template;
using TemplateEntity = QuickCode.DemoCms.SiteManagementModule.Domain.Entities.Template;
using QuickCode.DemoCms.SiteManagementModule.Domain.Enums;

namespace QuickCode.DemoCms.SiteManagementModule.Application.Mappings
{
    public static class TemplateMappings
    {
        public static List<TemplateDto> ToDto(this IEnumerable<TemplateEntity> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static TemplateDto ToDto(this TemplateEntity model)
        {
            return new TemplateDto
            {
                Id = model.Id,
                ThemeId = model.ThemeId,
                Name = model.Name,
                Key = model.Key,
                Description = model.Description,
                FilePath = model.FilePath
            };
        }

        public static TemplateEntity ToEntity(this TemplateDto model)
        {
            return new TemplateEntity
            {
                Id = model.Id,
                ThemeId = model.ThemeId,
                Name = model.Name,
                Key = model.Key,
                Description = model.Description,
                FilePath = model.FilePath
            };
        }
    }
}