//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.DemoCms.SiteManagementModule.Application.Dtos.Theme;
using ThemeEntity = QuickCode.DemoCms.SiteManagementModule.Domain.Entities.Theme;
using QuickCode.DemoCms.SiteManagementModule.Domain.Enums;

namespace QuickCode.DemoCms.SiteManagementModule.Application.Mappings
{
    public static class ThemeMappings
    {
        public static List<ThemeDto> ToDto(this IEnumerable<ThemeEntity> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static ThemeDto ToDto(this ThemeEntity model)
        {
            return new ThemeDto
            {
                Id = model.Id,
                Name = model.Name,
                Version = model.Version,
                Developer = model.Developer,
                RepositoryUrl = model.RepositoryUrl,
                IsActive = model.IsActive
            };
        }

        public static ThemeEntity ToEntity(this ThemeDto model)
        {
            return new ThemeEntity
            {
                Id = model.Id,
                Name = model.Name,
                Version = model.Version,
                Developer = model.Developer,
                RepositoryUrl = model.RepositoryUrl,
                IsActive = model.IsActive
            };
        }
    }
}