SELECT TOP 1 NM.[ID], NM.[NAME] 
FROM [NAVIGATION_MENUS] NM 
WHERE NM.[IsDeleted] = 0 
	AND NM.[SITE_ID] = @PRM_NAVIGATION_MENU_SITE_ID 
	AND NM.[LOCATION_KEY] = @PRM_NAVIGATION_MENU_LOCATION_KEY 
ORDER BY NM.[ID] 