SELECT NM.[ID], NM.[NAME], NM.[LOCATION_KEY] 
FROM [NAVIGATION_MENUS] NM 
WHERE NM.[IsDeleted] = 0 
	AND NM.[SITE_ID] = @PRM_NAVIGATION_MENU_SITE_ID 
ORDER BY NM.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 