SELECT D.[ID], D.[HOSTNAME], D.[IS_PRIMARY], D.[IS_ACTIVE] 
FROM [DOMAINS] D 
WHERE D.[IsDeleted] = 0 
	AND D.[SITE_ID] = @PRM_DOMAIN_SITE_ID 
ORDER BY D.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 