//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoCms.Common.Models;
using QuickCode.DemoCms.AssetManagementModule.Domain.Entities;
using QuickCode.DemoCms.AssetManagementModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.DemoCms.Common;
using QuickCode.DemoCms.Common.Extensions;
using QuickCode.DemoCms.Common.Helpers;
using QuickCode.DemoCms.AssetManagementModule.Persistence.Contexts;
using QuickCode.DemoCms.AssetManagementModule.Application.Dtos.AssetMetadatum;
using QuickCode.DemoCms.AssetManagementModule.Application.Mappings;
using QuickCode.DemoCms.AssetManagementModule.Persistence.Sql;
using QuickCode.DemoCms.AssetManagementModule.Domain.Enums;

namespace QuickCode.DemoCms.AssetManagementModule.Persistence.Repositories
{
    public partial class AssetMetadatumRepository : BaseRepository, IAssetMetadatumRepository
    {
        public async Task<RepoResponse<int>> UpdateMetadataValueAsync(int assetMetadatumAssetId, string assetMetadatumKey, UpdateMetadataValueRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling("AssetMetadatum", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.AssetMetadatum.Command.UpdateMetadataValue);
                var parameters = new
                {
                    ASSET_METADATA_VALUE = updateRequest.AssetMetadataValue,
                    PRM_ASSET_METADATA_ASSET_ID = assetMetadatumAssetId,
                    PRM_ASSET_METADATA_KEY = assetMetadatumKey
                };
                using var connection = await GetOpenConnectionAsync(_writeContext);
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result, "Success");
            });
        }
    }
}