SELECT P.[ID], P.[STATUS], P.[PUBLISH_DATE] 
FROM [POSTS] P 
WHERE P.[IsDeleted] = 0 
	AND P.[AUTHOR_ID] = @PRM_POST_AUTHOR_ID 
ORDER BY P.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 