SELECT P.[ID], P.[AUTHOR_ID], P.[PUBLISH_DATE] 
FROM [POSTS] P 
WHERE P.[IsDeleted] = 0 
	AND P.[STATUS] = @PRM_POST_STATUS 
ORDER BY P.[PUBLISH_DATE] DESC 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 