//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoCms.Common.Models;
using QuickCode.DemoCms.IdentityModule.Domain.Entities;
using QuickCode.DemoCms.IdentityModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.DemoCms.Common;
using QuickCode.DemoCms.Common.Extensions;
using QuickCode.DemoCms.Common.Helpers;
using QuickCode.DemoCms.IdentityModule.Persistence.Contexts;
using QuickCode.DemoCms.IdentityModule.Application.Dtos.PortalPageDefinition;
using QuickCode.DemoCms.IdentityModule.Application.Mappings;
using QuickCode.DemoCms.IdentityModule.Persistence.Sql;
using QuickCode.DemoCms.IdentityModule.Domain.Enums;

namespace QuickCode.DemoCms.IdentityModule.Persistence.Repositories
{
    public partial class PortalPageDefinitionRepository : BaseRepository, IPortalPageDefinitionRepository
    {
        public async Task<RepoResponse<List<GetPortalPageDefinitionsWithModuleNameResponseDto>>> GetPortalPageDefinitionsWithModuleNameAsync(string portalPageDefinitionModuleName)
        {
            return await ExecuteWithExceptionHandling("GetPortalPageDefinitionsWithModuleName", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.PortalPageDefinition.Query.GetPortalPageDefinitionsWithModuleName);
                var parameters = new
                {
                    PRM_PortalPageDefinition_ModuleName = portalPageDefinitionModuleName
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetPortalPageDefinitionsWithModuleNameResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in PortalPageDefinition");
            });
        }

        public async Task<RepoResponse<List<GetPortalPageDefinitionsWithModelNameResponseDto>>> GetPortalPageDefinitionsWithModelNameAsync(string portalPageDefinitionModelName)
        {
            return await ExecuteWithExceptionHandling("GetPortalPageDefinitionsWithModelName", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.PortalPageDefinition.Query.GetPortalPageDefinitionsWithModelName);
                var parameters = new
                {
                    PRM_PortalPageDefinition_ModelName = portalPageDefinitionModelName
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetPortalPageDefinitionsWithModelNameResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in PortalPageDefinition");
            });
        }

        public async Task<RepoResponse<bool>> ExistsPortalPageDefinitionsWithModuleNameAsync(string portalPageDefinitionModuleName)
        {
            return await ExecuteWithExceptionHandling("ExistsPortalPageDefinitionsWithModuleName", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.PortalPageDefinition.Query.ExistsPortalPageDefinitionsWithModuleName);
                var parameters = new
                {
                    PRM_PortalPageDefinition_ModuleName = portalPageDefinitionModuleName
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var exists = await connection.ExecuteScalarAsync<bool>(sql, parameters);
                return BuildBoolResponse(exists, $"Not found in PortalPageDefinition");
            });
        }

        public async Task<RepoResponse<bool>> ExistsPortalPageDefinitionsWithModelNameAsync(string portalPageDefinitionModelName)
        {
            return await ExecuteWithExceptionHandling("ExistsPortalPageDefinitionsWithModelName", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.PortalPageDefinition.Query.ExistsPortalPageDefinitionsWithModelName);
                var parameters = new
                {
                    PRM_PortalPageDefinition_ModelName = portalPageDefinitionModelName
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var exists = await connection.ExecuteScalarAsync<bool>(sql, parameters);
                return BuildBoolResponse(exists, $"Not found in PortalPageDefinition");
            });
        }
    }
}