//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoCms.Common.Models;
using QuickCode.DemoCms.AssetManagementModule.Domain.Entities;
using QuickCode.DemoCms.AssetManagementModule.Application.Dtos.AssetRendition;
using System.Threading.Tasks;
using QuickCode.DemoCms.AssetManagementModule.Domain.Enums;

namespace QuickCode.DemoCms.AssetManagementModule.Application.Interfaces.Repositories
{
    public partial interface IAssetRenditionRepository : IBaseRepository<AssetRenditionDto>
    {
        Task<RepoResponse<AssetRenditionDto>> GetByPkAsync(int id);
        Task<RepoResponse<List<GetRenditionsForAssetResponseDto>>> GetRenditionsForAssetAsync(int assetRenditionOriginalAssetId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<GetRenditionByNameResponseDto>> GetRenditionByNameAsync(int assetRenditionOriginalAssetId, string assetRenditionName);
    }
}