//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoCms.Common.Models;
using QuickCode.DemoCms.AssetManagementModule.Domain.Entities;
using QuickCode.DemoCms.AssetManagementModule.Application.Dtos.AssetFolder;
using System.Threading.Tasks;
using QuickCode.DemoCms.AssetManagementModule.Domain.Enums;

namespace QuickCode.DemoCms.AssetManagementModule.Application.Interfaces.Repositories
{
    public partial interface IAssetFolderRepository : IBaseRepository<AssetFolderDto>
    {
        Task<RepoResponse<AssetFolderDto>> GetByPkAsync(int id);
        Task<RepoResponse<List<GetRootFoldersResponseDto>>> GetRootFoldersAsync(int assetFolderParentFolderId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetSubfoldersResponseDto>>> GetSubfoldersAsync(int assetFolderParentFolderId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<SearchByNameResponseDto>>> SearchByNameAsync(string assetFolderName, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<GetByPathResponseDto>> GetByPathAsync(string assetFolderPath);
    }
}