//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoCms.Common.Models;
using QuickCode.DemoCms.SiteManagementModule.Domain.Entities;
using QuickCode.DemoCms.SiteManagementModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.DemoCms.Common;
using QuickCode.DemoCms.Common.Extensions;
using QuickCode.DemoCms.Common.Helpers;
using QuickCode.DemoCms.SiteManagementModule.Persistence.Contexts;
using QuickCode.DemoCms.SiteManagementModule.Application.Dtos.SiteSetting;
using QuickCode.DemoCms.SiteManagementModule.Application.Mappings;
using QuickCode.DemoCms.SiteManagementModule.Persistence.Sql;
using QuickCode.DemoCms.SiteManagementModule.Domain.Enums;

namespace QuickCode.DemoCms.SiteManagementModule.Persistence.Repositories
{
    public partial class SiteSettingRepository : BaseRepository, ISiteSettingRepository
    {
        public async Task<RepoResponse<List<GetSettingsForSiteResponseDto>>> GetSettingsForSiteAsync(int siteSettingSiteId)
        {
            return await ExecuteWithExceptionHandling("GetSettingsForSite", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.SiteSetting.Query.GetSettingsForSite);
                var parameters = new
                {
                    PRM_SITE_SETTING_SITE_ID = siteSettingSiteId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetSettingsForSiteResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in SiteSetting");
            });
        }

        public async Task<RepoResponse<GetSettingByKeyResponseDto>> GetSettingByKeyAsync(int siteSettingSiteId, string siteSettingKey)
        {
            return await ExecuteWithExceptionHandling("GetSettingByKey", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.SiteSetting.Query.GetSettingByKey);
                var parameters = new
                {
                    PRM_SITE_SETTING_SITE_ID = siteSettingSiteId,
                    PRM_SITE_SETTING_KEY = siteSettingKey
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<GetSettingByKeyResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in SiteSetting");
            });
        }
    }
}