SELECT CV.[ID], CV.[VERSION_NUMBER], CV.[CREATED_BY_USER_ID], CV.[CREATED_DATE] 
FROM [CONTENT_VERSIONS] CV 
WHERE CV.[IsDeleted] = 0 
	AND CV.[CONTENT_TYPE_KIND] = @PRM_CONTENT_VERSION_CONTENT_TYPE_KIND 
	AND CV.[CONTENT_ID] = @PRM_CONTENT_VERSION_CONTENT_ID 
	AND CV.[TRANSLATION_ID] = @PRM_CONTENT_VERSION_TRANSLATION_ID 
ORDER BY CV.[VERSION_NUMBER] DESC 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 