//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoCms.Common.Models;
using QuickCode.DemoCms.ContentManagementModule.Domain.Entities;
using QuickCode.DemoCms.ContentManagementModule.Application.Dtos.ContentTag;
using System.Threading.Tasks;
using QuickCode.DemoCms.ContentManagementModule.Domain.Enums;

namespace QuickCode.DemoCms.ContentManagementModule.Application.Interfaces.Repositories
{
    public partial interface IContentTagRepository : IBaseRepository<ContentTagDto>
    {
        Task<RepoResponse<ContentTagDto>> GetByPkAsync(ContentKind contentTypeKind, int contentId, int tagId);
        Task<RepoResponse<List<GetTagsForContentResponseDto>>> GetTagsForContentAsync(ContentKind contentTagContentTypeKind, int contentTagContentId);
        Task<RepoResponse<List<GetContentForTagResponseDto>>> GetContentForTagAsync(int contentTagTagId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<int>> RemoveTagFromContentAsync(ContentKind contentTagContentTypeKind, int contentTagContentId, int contentTagTagId);
        Task<RepoResponse<int>> RemoveAllTagsFromContentAsync(ContentKind contentTagContentTypeKind, int contentTagContentId);
    }
}