//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoCms.Common.Models;
using QuickCode.DemoCms.ContentManagementModule.Domain.Entities;
using QuickCode.DemoCms.ContentManagementModule.Application.Dtos.PageTranslation;
using System.Threading.Tasks;
using QuickCode.DemoCms.ContentManagementModule.Domain.Enums;

namespace QuickCode.DemoCms.ContentManagementModule.Application.Interfaces.Repositories
{
    public partial interface IPageTranslationRepository : IBaseRepository<PageTranslationDto>
    {
        Task<RepoResponse<PageTranslationDto>> GetByPkAsync(int id);
        Task<RepoResponse<List<GetByPageIdResponseDto>>> GetByPageIdAsync(int pageTranslationPageId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<GetByPageAndLanguageResponseDto>> GetByPageAndLanguageAsync(int pageTranslationPageId, string pageTranslationLanguageCode);
        Task<RepoResponse<GetBySlugAndLanguageResponseDto>> GetBySlugAndLanguageAsync(string pageTranslationLanguageCode, string pageTranslationSlug);
        Task<RepoResponse<bool>> CheckSlugExistsAsync(string pageTranslationLanguageCode, string pageTranslationSlug);
    }
}