//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoCms.Common.Models;
using QuickCode.DemoCms.SiteManagementModule.Domain.Entities;
using QuickCode.DemoCms.SiteManagementModule.Application.Dtos.NavigationMenu;
using System.Threading.Tasks;
using QuickCode.DemoCms.SiteManagementModule.Domain.Enums;

namespace QuickCode.DemoCms.SiteManagementModule.Application.Interfaces.Repositories
{
    public partial interface INavigationMenuRepository : IBaseRepository<NavigationMenuDto>
    {
        Task<RepoResponse<NavigationMenuDto>> GetByPkAsync(int id);
        Task<RepoResponse<List<GetBySiteIdResponseDto>>> GetBySiteIdAsync(int navigationMenuSiteId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<GetByLocationResponseDto>> GetByLocationAsync(int navigationMenuSiteId, string navigationMenuLocationKey);
    }
}