//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoCms.Common.Models;
using QuickCode.DemoCms.SiteManagementModule.Domain.Entities;
using QuickCode.DemoCms.SiteManagementModule.Application.Dtos.SiteSetting;
using System.Threading.Tasks;
using QuickCode.DemoCms.SiteManagementModule.Domain.Enums;

namespace QuickCode.DemoCms.SiteManagementModule.Application.Interfaces.Repositories
{
    public partial interface ISiteSettingRepository : IBaseRepository<SiteSettingDto>
    {
        Task<RepoResponse<SiteSettingDto>> GetByPkAsync(int id);
        Task<RepoResponse<List<GetSettingsForSiteResponseDto>>> GetSettingsForSiteAsync(int siteSettingSiteId);
        Task<RepoResponse<GetSettingByKeyResponseDto>> GetSettingByKeyAsync(int siteSettingSiteId, string siteSettingKey);
        Task<RepoResponse<int>> UpdateValueAsync(int siteSettingSiteId, string siteSettingKey, UpdateValueRequestDto updateRequest);
    }
}