//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoCms.Common.Models;
using QuickCode.DemoCms.SiteManagementModule.Domain.Entities;
using QuickCode.DemoCms.SiteManagementModule.Application.Dtos.SiteLanguage;
using System.Threading.Tasks;
using QuickCode.DemoCms.SiteManagementModule.Domain.Enums;

namespace QuickCode.DemoCms.SiteManagementModule.Application.Interfaces.Repositories
{
    public partial interface ISiteLanguageRepository : IBaseRepository<SiteLanguageDto>
    {
        Task<RepoResponse<SiteLanguageDto>> GetByPkAsync(int siteId, int languageId);
        Task<RepoResponse<List<GetLanguagesForSiteResponseDto>>> GetLanguagesForSiteAsync(int siteLanguageSiteId, bool siteLanguageIsEnabled);
        Task<RepoResponse<int>> EnableLanguageAsync(int siteLanguageSiteId, int siteLanguageLanguageId, EnableLanguageRequestDto updateRequest);
        Task<RepoResponse<int>> DisableLanguageAsync(int siteLanguageSiteId, int siteLanguageLanguageId, DisableLanguageRequestDto updateRequest);
    }
}