//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoCms.Common.Models;
using QuickCode.DemoCms.ContentManagementModule.Domain.Entities;
using QuickCode.DemoCms.ContentManagementModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.DemoCms.Common;
using QuickCode.DemoCms.Common.Extensions;
using QuickCode.DemoCms.Common.Helpers;
using QuickCode.DemoCms.ContentManagementModule.Persistence.Contexts;
using QuickCode.DemoCms.ContentManagementModule.Application.Dtos.Page;
using QuickCode.DemoCms.ContentManagementModule.Application.Mappings;
using QuickCode.DemoCms.ContentManagementModule.Persistence.Sql;
using QuickCode.DemoCms.ContentManagementModule.Domain.Enums;

namespace QuickCode.DemoCms.ContentManagementModule.Persistence.Repositories
{
    public partial class PageRepository : BaseRepository, IPageRepository
    {
        public async Task<RepoResponse<int>> PublishAsync(int pageId, PublishRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling("Page", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Page.Command.Publish);
                var parameters = new
                {
                    PRM_PAGE_ID = pageId
                };
                using var connection = await GetOpenConnectionAsync(_writeContext);
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result, "Success");
            });
        }

        public async Task<RepoResponse<int>> ArchiveAsync(int pageId, ArchiveRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling("Page", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Page.Command.Archive);
                var parameters = new
                {
                    PRM_PAGE_ID = pageId
                };
                using var connection = await GetOpenConnectionAsync(_writeContext);
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result, "Success");
            });
        }

        public async Task<RepoResponse<int>> RevertToDraftAsync(int pageId, RevertToDraftRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling("Page", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Page.Command.RevertToDraft);
                var parameters = new
                {
                    PRM_PAGE_ID = pageId
                };
                using var connection = await GetOpenConnectionAsync(_writeContext);
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result, "Success");
            });
        }

        public async Task<RepoResponse<int>> RequestReviewAsync(int pageId, RequestReviewRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling("Page", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Page.Command.RequestReview);
                var parameters = new
                {
                    PRM_PAGE_ID = pageId
                };
                using var connection = await GetOpenConnectionAsync(_writeContext);
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result, "Success");
            });
        }
    }
}