//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoCms.Common.Models;
using QuickCode.DemoCms.AssetManagementModule.Domain.Entities;
using QuickCode.DemoCms.AssetManagementModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.DemoCms.Common;
using QuickCode.DemoCms.Common.Extensions;
using QuickCode.DemoCms.Common.Helpers;
using QuickCode.DemoCms.AssetManagementModule.Persistence.Contexts;
using QuickCode.DemoCms.AssetManagementModule.Application.Dtos.AssetTranslation;
using QuickCode.DemoCms.AssetManagementModule.Application.Mappings;
using QuickCode.DemoCms.AssetManagementModule.Persistence.Sql;
using QuickCode.DemoCms.AssetManagementModule.Domain.Enums;

namespace QuickCode.DemoCms.AssetManagementModule.Persistence.Repositories
{
    public partial class AssetTranslationRepository : BaseRepository, IAssetTranslationRepository
    {
        public async Task<RepoResponse<List<GetByAssetIdResponseDto>>> GetByAssetIdAsync(int assetTranslationAssetId, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling("GetByAssetId", async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetByAssetIdResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.AssetTranslation.Query.GetByAssetId);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_ASSET_TRANSLATION_ASSET_ID = assetTranslationAssetId,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    using var connection = await GetOpenConnectionAsync(_readContext);
                    var values = await connection.QueryAsync<GetByAssetIdResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in AssetTranslation");
                }
            });
        }

        public async Task<RepoResponse<GetByAssetAndLanguageResponseDto>> GetByAssetAndLanguageAsync(int assetTranslationAssetId, string assetTranslationLanguageCode)
        {
            return await ExecuteWithExceptionHandling("GetByAssetAndLanguage", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.AssetTranslation.Query.GetByAssetAndLanguage);
                var parameters = new
                {
                    PRM_ASSET_TRANSLATION_ASSET_ID = assetTranslationAssetId,
                    PRM_ASSET_TRANSLATION_LANGUAGE_CODE = assetTranslationLanguageCode
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<GetByAssetAndLanguageResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in AssetTranslation");
            });
        }
    }
}