//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoCms.Common.Models;
using QuickCode.DemoCms.LocalizationModule.Domain.Entities;
using QuickCode.DemoCms.LocalizationModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.DemoCms.Common;
using QuickCode.DemoCms.Common.Extensions;
using QuickCode.DemoCms.Common.Helpers;
using QuickCode.DemoCms.LocalizationModule.Persistence.Contexts;
using QuickCode.DemoCms.LocalizationModule.Application.Dtos.ResourceFile;
using QuickCode.DemoCms.LocalizationModule.Application.Mappings;
using QuickCode.DemoCms.LocalizationModule.Persistence.Sql;
using QuickCode.DemoCms.LocalizationModule.Domain.Enums;

namespace QuickCode.DemoCms.LocalizationModule.Persistence.Repositories
{
    public partial class ResourceFileRepository : BaseRepository, IResourceFileRepository
    {
        public async Task<RepoResponse<int>> MarkAsProcessedAsync(int resourceFileId, MarkAsProcessedRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling("ResourceFile", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.ResourceFile.Command.MarkAsProcessed);
                var parameters = new
                {
                    PRM_RESOURCE_FILE_ID = resourceFileId
                };
                using var connection = await GetOpenConnectionAsync(_writeContext);
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result, "Success");
            });
        }

        public async Task<RepoResponse<int>> MarkAsFailedAsync(int resourceFileId, MarkAsFailedRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling("ResourceFile", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.ResourceFile.Command.MarkAsFailed);
                var parameters = new
                {
                    PRM_RESOURCE_FILE_ID = resourceFileId
                };
                using var connection = await GetOpenConnectionAsync(_writeContext);
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result, "Success");
            });
        }
    }
}