SELECT TOP 1 AR.[ID], AR.[STORAGE_PATH], AR.[MIME_TYPE] 
FROM [ASSET_RENDITIONS] AR 
WHERE AR.[IsDeleted] = 0 
	AND AR.[ORIGINAL_ASSET_ID] = @PRM_ASSET_RENDITION_ORIGINAL_ASSET_ID 
	AND AR.[NAME] = @PRM_ASSET_RENDITION_NAME 
ORDER BY AR.[ID] 