SELECT AR.[ID], AR.[NAME], AR.[WIDTH], AR.[HEIGHT], AR.[FILE_SIZE_BYTES], AR.[MIME_TYPE] 
FROM [ASSET_RENDITIONS] AR 
WHERE AR.[IsDeleted] = 0 
	AND AR.[ORIGINAL_ASSET_ID] = @PRM_ASSET_RENDITION_ORIGINAL_ASSET_ID 
ORDER BY AR.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 