//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.DemoCms.LocalizationModule.Application.Dtos.LanguageFallback;
using QuickCode.DemoCms.LocalizationModule.Domain.Entities;
using QuickCode.DemoCms.LocalizationModule.Domain.Enums;

namespace QuickCode.DemoCms.LocalizationModule.Application.Mappings
{
    public static class LanguageFallbackMappings
    {
        public static List<LanguageFallbackDto> ToDto(this IEnumerable<LanguageFallback> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static LanguageFallbackDto ToDto(this LanguageFallback model)
        {
            return new LanguageFallbackDto
            {
                LanguageId = model.LanguageId,
                FallbackLanguageId = model.FallbackLanguageId,
                Priority = model.Priority
            };
        }

        public static LanguageFallback ToEntity(this LanguageFallbackDto model)
        {
            return new LanguageFallback
            {
                LanguageId = model.LanguageId,
                FallbackLanguageId = model.FallbackLanguageId,
                Priority = model.Priority
            };
        }
    }
}