//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.DemoCms.LocalizationModule.Application.Dtos.Language;
using LanguageEntity = QuickCode.DemoCms.LocalizationModule.Domain.Entities.Language;
using QuickCode.DemoCms.LocalizationModule.Domain.Enums;

namespace QuickCode.DemoCms.LocalizationModule.Application.Mappings
{
    public static class LanguageMappings
    {
        public static List<LanguageDto> ToDto(this IEnumerable<LanguageEntity> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static LanguageDto ToDto(this LanguageEntity model)
        {
            return new LanguageDto
            {
                Id = model.Id,
                Code = model.Code,
                Name = model.Name,
                IsDefault = model.IsDefault,
                IsActive = model.IsActive
            };
        }

        public static LanguageEntity ToEntity(this LanguageDto model)
        {
            return new LanguageEntity
            {
                Id = model.Id,
                Code = model.Code,
                Name = model.Name,
                IsDefault = model.IsDefault,
                IsActive = model.IsActive
            };
        }
    }
}