//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.DemoCms.LocalizationModule.Application.Dtos.TranslationValue;
using QuickCode.DemoCms.LocalizationModule.Domain.Entities;
using QuickCode.DemoCms.LocalizationModule.Domain.Enums;

namespace QuickCode.DemoCms.LocalizationModule.Application.Mappings
{
    public static class TranslationValueMappings
    {
        public static List<TranslationValueDto> ToDto(this IEnumerable<TranslationValue> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static TranslationValueDto ToDto(this TranslationValue model)
        {
            return new TranslationValueDto
            {
                Id = model.Id,
                KeyId = model.KeyId,
                LanguageId = model.LanguageId,
                Value = model.Value,
                UpdatedDate = model.UpdatedDate
            };
        }

        public static TranslationValue ToEntity(this TranslationValueDto model)
        {
            return new TranslationValue
            {
                Id = model.Id,
                KeyId = model.KeyId,
                LanguageId = model.LanguageId,
                Value = model.Value,
                UpdatedDate = model.UpdatedDate
            };
        }
    }
}