//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.DemoCms.SiteManagementModule.Domain.Enums;

namespace QuickCode.DemoCms.SiteManagementModule.Application.Dtos.Theme
{
    public record ThemeDto
    {
        public int Id { get; init; }
        public string Name { get; init; }
        public string Version { get; init; }
        public string Developer { get; init; }
        public string RepositoryUrl { get; init; }
        public bool IsActive { get; init; }
    }
}