//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.DemoCms.Common.Models;
using QuickCode.DemoCms.SiteManagementModule.Domain.Entities;
using QuickCode.DemoCms.SiteManagementModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.DemoCms.Common;
using QuickCode.DemoCms.Common.Extensions;
using QuickCode.DemoCms.Common.Helpers;
using QuickCode.DemoCms.SiteManagementModule.Persistence.Contexts;
using QuickCode.DemoCms.SiteManagementModule.Application.Dtos.NavigationItem;
using QuickCode.DemoCms.SiteManagementModule.Application.Mappings;
using QuickCode.DemoCms.SiteManagementModule.Persistence.Sql;
using QuickCode.DemoCms.SiteManagementModule.Domain.Enums;

namespace QuickCode.DemoCms.SiteManagementModule.Persistence.Repositories
{
    public partial class NavigationItemRepository : BaseRepository, INavigationItemRepository
    {
        public async Task<RepoResponse<int>> UpdateSortOrderAsync(int navigationItemId, UpdateSortOrderRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling("NavigationItem", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.NavigationItem.Command.UpdateSortOrder);
                var parameters = new
                {
                    NAVIGATION_ITEM_SORT_ORDER = updateRequest.NavigationItemSortOrder,
                    PRM_NAVIGATION_ITEM_ID = navigationItemId
                };
                using var connection = await GetOpenConnectionAsync(_writeContext);
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result, "Success");
            });
        }
    }
}