SELECT P.[ID], P.[CONTENT_TYPE_ID], P.[PARENT_PAGE_ID], P.[PUBLISH_DATE] 
FROM [PAGES] P 
WHERE P.[IsDeleted] = 0 
	AND P.[STATUS] = @PRM_PAGE_STATUS 
ORDER BY P.[PUBLISH_DATE] DESC 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 