//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.DemoCms.SiteManagementModule.Domain.Enums;

namespace QuickCode.DemoCms.SiteManagementModule.Application.Dtos.NavigationItem
{
    public record GetByMenuIdResponseDto
    {
        public int Id { get; init; }
        public int ParentItemId { get; init; }
        public NavigationItemType Type { get; init; }
        public string Label { get; init; }
        public string Url { get; init; }
        public int PageId { get; init; }
        public int SortOrder { get; init; }
        public bool IsVisible { get; init; }
    }
}